package com.pandorasoft.precogs.templates;
import com.sample.drools.pojo.RuleOutput;
import com.sample.drools.pojo.FactorContext
import com.alibaba.fastjson.JSON;
global RuleOutput ruleOutput;

rule "rule-age-1"
when
    context:FactorContext(age<="21" || age>="45")
then
    System.out.println("rule.name:" + kcontext.getRule().getName());
    System.out.println(JSON.toJSONString(context));
    ruleOutput.setDeny(true);
end

