@startuml

start
:用户注册;
note:/snack/createChannelUser

:添加visa卡（事件源）;
note:/snack/addVisaCard

:用户信息补全;
note:/snack/operate/userInfo

:CKA校验（准入）;
note:/snack/submitInvestmentAssessment

:风险和风险等级检测;
note: /snack/submitInvestmentAssessment

:optIn产品（ilp和其他产品）;
note:/snack/optInNew

:设置weekCap;
note:/snack/operate/weeklyCap

:分别为optIn的产品增加事件源;
note:/snack/operate/trigger

:触发事件源;
note:/snack/operate/trigger

:周末跑批处理当周trigger;

:周一晚上生成周一的价格;

:周二跑批处理处理价格日为周一的trigger txn;


stop
@enduml
